/*
BookxNote Local OCR API

BookxNote 本地 OCR 服务 API 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostOcrByBxnLocalOcr400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostOcrByBxnLocalOcr400Response{}

// PostOcrByBxnLocalOcr400Response struct for PostOcrByBxnLocalOcr400Response
type PostOcrByBxnLocalOcr400Response struct {
	// 错误码
	Code *int32 `json:"code,omitempty"`
	// 错误信息描述
	Msg *string `json:"msg,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PostOcrByBxnLocalOcr400Response PostOcrByBxnLocalOcr400Response

// NewPostOcrByBxnLocalOcr400Response instantiates a new PostOcrByBxnLocalOcr400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostOcrByBxnLocalOcr400Response() *PostOcrByBxnLocalOcr400Response {
	this := PostOcrByBxnLocalOcr400Response{}
	return &this
}

// NewPostOcrByBxnLocalOcr400ResponseWithDefaults instantiates a new PostOcrByBxnLocalOcr400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostOcrByBxnLocalOcr400ResponseWithDefaults() *PostOcrByBxnLocalOcr400Response {
	this := PostOcrByBxnLocalOcr400Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PostOcrByBxnLocalOcr400Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostOcrByBxnLocalOcr400Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PostOcrByBxnLocalOcr400Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *PostOcrByBxnLocalOcr400Response) SetCode(v int32) {
	o.Code = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *PostOcrByBxnLocalOcr400Response) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostOcrByBxnLocalOcr400Response) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *PostOcrByBxnLocalOcr400Response) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *PostOcrByBxnLocalOcr400Response) SetMsg(v string) {
	o.Msg = &v
}

func (o PostOcrByBxnLocalOcr400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostOcrByBxnLocalOcr400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostOcrByBxnLocalOcr400Response) UnmarshalJSON(data []byte) (err error) {
	varPostOcrByBxnLocalOcr400Response := _PostOcrByBxnLocalOcr400Response{}

	err = json.Unmarshal(data, &varPostOcrByBxnLocalOcr400Response)

	if err != nil {
		return err
	}

	*o = PostOcrByBxnLocalOcr400Response(varPostOcrByBxnLocalOcr400Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "msg")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePostOcrByBxnLocalOcr400Response struct {
	value *PostOcrByBxnLocalOcr400Response
	isSet bool
}

func (v NullablePostOcrByBxnLocalOcr400Response) Get() *PostOcrByBxnLocalOcr400Response {
	return v.value
}

func (v *NullablePostOcrByBxnLocalOcr400Response) Set(val *PostOcrByBxnLocalOcr400Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostOcrByBxnLocalOcr400Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostOcrByBxnLocalOcr400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostOcrByBxnLocalOcr400Response(val *PostOcrByBxnLocalOcr400Response) *NullablePostOcrByBxnLocalOcr400Response {
	return &NullablePostOcrByBxnLocalOcr400Response{value: val, isSet: true}
}

func (v NullablePostOcrByBxnLocalOcr400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostOcrByBxnLocalOcr400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


