/*
BookxNote Local OCR API

BookxNote 本地 OCR 服务 API 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1OcrByBxnLocalOcrPost400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1OcrByBxnLocalOcrPost400Response{}

// V1OcrByBxnLocalOcrPost400Response struct for V1OcrByBxnLocalOcrPost400Response
type V1OcrByBxnLocalOcrPost400Response struct {
	// 错误码
	Code *int32 `json:"code,omitempty"`
	// 错误信息描述
	Msg *string `json:"msg,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1OcrByBxnLocalOcrPost400Response V1OcrByBxnLocalOcrPost400Response

// NewV1OcrByBxnLocalOcrPost400Response instantiates a new V1OcrByBxnLocalOcrPost400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1OcrByBxnLocalOcrPost400Response() *V1OcrByBxnLocalOcrPost400Response {
	this := V1OcrByBxnLocalOcrPost400Response{}
	return &this
}

// NewV1OcrByBxnLocalOcrPost400ResponseWithDefaults instantiates a new V1OcrByBxnLocalOcrPost400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1OcrByBxnLocalOcrPost400ResponseWithDefaults() *V1OcrByBxnLocalOcrPost400Response {
	this := V1OcrByBxnLocalOcrPost400Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *V1OcrByBxnLocalOcrPost400Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1OcrByBxnLocalOcrPost400Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *V1OcrByBxnLocalOcrPost400Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *V1OcrByBxnLocalOcrPost400Response) SetCode(v int32) {
	o.Code = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *V1OcrByBxnLocalOcrPost400Response) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1OcrByBxnLocalOcrPost400Response) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *V1OcrByBxnLocalOcrPost400Response) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *V1OcrByBxnLocalOcrPost400Response) SetMsg(v string) {
	o.Msg = &v
}

func (o V1OcrByBxnLocalOcrPost400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1OcrByBxnLocalOcrPost400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1OcrByBxnLocalOcrPost400Response) UnmarshalJSON(data []byte) (err error) {
	varV1OcrByBxnLocalOcrPost400Response := _V1OcrByBxnLocalOcrPost400Response{}

	err = json.Unmarshal(data, &varV1OcrByBxnLocalOcrPost400Response)

	if err != nil {
		return err
	}

	*o = V1OcrByBxnLocalOcrPost400Response(varV1OcrByBxnLocalOcrPost400Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "msg")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1OcrByBxnLocalOcrPost400Response struct {
	value *V1OcrByBxnLocalOcrPost400Response
	isSet bool
}

func (v NullableV1OcrByBxnLocalOcrPost400Response) Get() *V1OcrByBxnLocalOcrPost400Response {
	return v.value
}

func (v *NullableV1OcrByBxnLocalOcrPost400Response) Set(val *V1OcrByBxnLocalOcrPost400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1OcrByBxnLocalOcrPost400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1OcrByBxnLocalOcrPost400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1OcrByBxnLocalOcrPost400Response(val *V1OcrByBxnLocalOcrPost400Response) *NullableV1OcrByBxnLocalOcrPost400Response {
	return &NullableV1OcrByBxnLocalOcrPost400Response{value: val, isSet: true}
}

func (v NullableV1OcrByBxnLocalOcrPost400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1OcrByBxnLocalOcrPost400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


