/*
BookxNote Local OCR API

BookxNote 本地 OCR 服务 API 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1OcrByBxnLocalOcrPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1OcrByBxnLocalOcrPost200Response{}

// V1OcrByBxnLocalOcrPost200Response struct for V1OcrByBxnLocalOcrPost200Response
type V1OcrByBxnLocalOcrPost200Response struct {
	// 状态码，0表示成功
	Code *int32 `json:"code,omitempty"`
	// 状态信息
	Msg *string `json:"msg,omitempty"`
	Data *V1OcrByBxnLocalOcrPost200ResponseData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1OcrByBxnLocalOcrPost200Response V1OcrByBxnLocalOcrPost200Response

// NewV1OcrByBxnLocalOcrPost200Response instantiates a new V1OcrByBxnLocalOcrPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1OcrByBxnLocalOcrPost200Response() *V1OcrByBxnLocalOcrPost200Response {
	this := V1OcrByBxnLocalOcrPost200Response{}
	return &this
}

// NewV1OcrByBxnLocalOcrPost200ResponseWithDefaults instantiates a new V1OcrByBxnLocalOcrPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1OcrByBxnLocalOcrPost200ResponseWithDefaults() *V1OcrByBxnLocalOcrPost200Response {
	this := V1OcrByBxnLocalOcrPost200Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *V1OcrByBxnLocalOcrPost200Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1OcrByBxnLocalOcrPost200Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *V1OcrByBxnLocalOcrPost200Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *V1OcrByBxnLocalOcrPost200Response) SetCode(v int32) {
	o.Code = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *V1OcrByBxnLocalOcrPost200Response) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1OcrByBxnLocalOcrPost200Response) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *V1OcrByBxnLocalOcrPost200Response) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *V1OcrByBxnLocalOcrPost200Response) SetMsg(v string) {
	o.Msg = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *V1OcrByBxnLocalOcrPost200Response) GetData() V1OcrByBxnLocalOcrPost200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret V1OcrByBxnLocalOcrPost200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1OcrByBxnLocalOcrPost200Response) GetDataOk() (*V1OcrByBxnLocalOcrPost200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *V1OcrByBxnLocalOcrPost200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given V1OcrByBxnLocalOcrPost200ResponseData and assigns it to the Data field.
func (o *V1OcrByBxnLocalOcrPost200Response) SetData(v V1OcrByBxnLocalOcrPost200ResponseData) {
	o.Data = &v
}

func (o V1OcrByBxnLocalOcrPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1OcrByBxnLocalOcrPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1OcrByBxnLocalOcrPost200Response) UnmarshalJSON(data []byte) (err error) {
	varV1OcrByBxnLocalOcrPost200Response := _V1OcrByBxnLocalOcrPost200Response{}

	err = json.Unmarshal(data, &varV1OcrByBxnLocalOcrPost200Response)

	if err != nil {
		return err
	}

	*o = V1OcrByBxnLocalOcrPost200Response(varV1OcrByBxnLocalOcrPost200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "msg")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1OcrByBxnLocalOcrPost200Response struct {
	value *V1OcrByBxnLocalOcrPost200Response
	isSet bool
}

func (v NullableV1OcrByBxnLocalOcrPost200Response) Get() *V1OcrByBxnLocalOcrPost200Response {
	return v.value
}

func (v *NullableV1OcrByBxnLocalOcrPost200Response) Set(val *V1OcrByBxnLocalOcrPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1OcrByBxnLocalOcrPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1OcrByBxnLocalOcrPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1OcrByBxnLocalOcrPost200Response(val *V1OcrByBxnLocalOcrPost200Response) *NullableV1OcrByBxnLocalOcrPost200Response {
	return &NullableV1OcrByBxnLocalOcrPost200Response{value: val, isSet: true}
}

func (v NullableV1OcrByBxnLocalOcrPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1OcrByBxnLocalOcrPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


