name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read
  issues: read

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            suffix: ""
            artifacts: "*.tar.gz"
          - os: windows-latest
            goos: windows
            goarch: amd64
            suffix: ".exe"
            artifacts: "*.zip"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Packaging
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          make package
        shell: bash

      - name: Build Changelog
        if: startsWith(github.ref, 'refs/tags/')
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Release Template
        if: startsWith(github.ref, 'refs/tags/')
        id: release_template
        run: |
          template=$(cat .github/release-template.md)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "${template/-VERSION-/${{ github.ref_name }}}" >> $GITHUB_OUTPUT
          echo "${{ steps.github_release.outputs.changelog }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/${{ matrix.artifacts }}
          body: ${{ steps.release_template.outputs.content }}
          append_body: true
          draft: true
          fail_on_unmatched_files: true

      - name: Upload artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/${{ matrix.artifacts }}
          retention-days: 5